[theme]
base="dark"
primaryColor="#00bcd4"
backgroundColor="#0f172a"
secondaryBackgroundColor="#111827"
textColor="#f1f5f9"
font="sans serif"
[db]
postgresql+psycopg2://postgres:Guschiara30$@db.yrckqkbgaqscbuptihgs.supabase.co:5432/postgres