[theme]
base="dark"
primaryColor="#00BFFF"
backgroundColor="#0E1117"
secondaryBackgroundColor="#161B22"
textColor="#FAFAFA"
font="sans serif"
[db]
postgresql+psycopg2://postgres:Guschiara30%24@db.yrckqkbgaqscbuptihgs.supabase.co:5432/postgres